version: "3"
services:
    msprjava_db:
        image: 'postgres:13.1-alpine'
        container_name: msprjava_db
        environment:
            - POSTGRES_DB=msprjava
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 6000:5432

    msprjava_adminer:
        image: adminer
        restart: always
        ports:
            - 5000:8080

    #msprjava_api:
    #    container_name: "msprjava_api"
    #    image: msprjava_api
    #    ports:
    #    - 8080:8080
    #    build:
    #        context: ./msprjava
    #        dockerfile: Dockerfile
    #    depends_on:
    #        - msprjava_db
