listeners:
- query_port: 25565
  motd: mc.epsiwis.fr
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - main
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 50
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.list
  admin:
  - bungeecord.command.server
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: b929f95d-f1f9-4d6c-bec5-c3313caf0c34
inject_commands: false
player_limit: -1
ip_forward: false
groups:
  aymnms:
  - default
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  main:
    restricted: false
    motd: |2-
                   &9&lmc.epsiwis.fr &8[&71.8 &8-> &71.17.1&8]
                         &6Serveur Survie
    address: epsiwis-main:25566
  event:
    restricted: false
    motd: '&1Event epsiwis'
    address: epsiwis-event:25567
